# Generated by Django 5.0.6 on 2024-06-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=50)),
                ('studentname', models.CharField(max_length=255, null=True)),
                ('farthername', models.CharField(max_length=255, null=True)),
                ('mothername', models.CharField(max_length=255, null=True)),
                ('caursename', models.CharField(max_length=255, null=True)),
                ('caursestatus', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(default='1', max_length=255)),
                ('date', models.DateField(null=True)),
                ('photo', models.FileField(max_length=255, null=True, upload_to='myimage/')),
            ],
        ),
    ]
